name: CI
on: push

jobs:
  Test:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build --if-exits
      - run: npm run lint --if-exists
      - run: npm run test --if-exists
      - run: npm run coverage --if-exists
