name: CI
on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run build
      - run: npm run format
      - uses: actions/upload-artifact@v2
        with:
          name: lib
          path: lib/
      - uses: actions/upload-artifact@v2
        with:
          name: aod.min
          path: aod.min*
  Test:
    needs: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14, 15]
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@v2
        with:
          name: lib
          path: lib
      - run: npm install
      - run: npm run lint --if-exists
      - run: npm run coverage --if-exists
