name: Nightly

on:
  schedule:
    # try picking something thats not 0 0
    - cron: "7 9 * * *"
jobs:
  NightlyImportCheck:
    runs-on: ubuntu-latest
    steps:
      run: npm i @johntalton/and-other-delights
      run: echo "const { BitUtils } = require('@johntalton/and-other-delights');BitUtil.packBits([[7, 1]], [1])" > import-test.cjs
      run: echo "import { BitUtils } from '@johntalton/and-other-delights';BitUtil.packBits([[7, 1]], [1])" > import-test.mjs
      run: node import-test.cjs
      # run: node import-test.mjs
