name: Close Stale
permissions:
  actions: write
  contents: read
  issues: write
  pull-requests: write
on:
  schedule:
  - cron: "37 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v10
      with:
        stale-issue-message: 'This issue is getting a bit stale... the robots will come for it soon unless un-staled or comment or magic'
        stale-issue-label: 'Stale'
        days-before-close: -1
